### ISSUE TITLE
Compilation fails on Linux

### ISSUE THREAD

**Issue by paramat** [MultiCraftProject/MultiCraft#140]
At commit 43625aafeea725a09c90ea93dcb8e07fb747a6b0 25 May.
Error message:
```
/tmp/ccz3PngF.ltrans24.ltrans.o: In function `FontEngine::initFont(unsigned int, FontMode)':
<artificial>:(.text._ZN10FontEngine8initFontEj8FontMode+0x3a3): undefined reference to `irr::gui::CGUITTFont::createTTFont(irr::gui::IGUIEnvironment*, irr::core::string<char, irr::core::irrAllocator<char> > const&, unsigned int, bool, bool, unsigned int, unsigned int)'
<artificial>:(.text._ZN10FontEngine8initFontEj8FontMode+0xf96): undefined reference to `irr::gui::CGUITTFont::createTTFont(irr::gui::IGUIEnvironment*, irr::core::string<char, irr::core::irrAllocator<char> > const&, unsigned int, bool, bool, unsigned int, unsigned int)'
<artificial>:(.text._ZN10FontEngine8initFontEj8FontMode+0x10cd): undefined reference to `irr::gui::CGUITTFont::createTTFont(irr::gui::IGUIEnvironment*, irr::core::string<char, irr::core::irrAllocator<char> > const&, unsigned int, bool, bool, unsigned int, unsigned int)'
<artificial>:(.text._ZN10FontEngine8initFontEj8FontMode+0x11ee): undefined reference to `irr::gui::CGUITTFont::createTTFont(irr::gui::IGUIEnvironment*, irr::core::string<char, irr::core::irrAllocator<char> > const&, unsigned int, bool, bool, unsigned int, unsigned int)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/MultiCraft.dir/build.make:5242: recipe for target 'bin/MultiCraft' failed
make[2]: *** [bin/MultiCraft] Error 1
CMakeFiles/Makefile2:272: recipe for target 'src/CMakeFiles/MultiCraft.dir/all' failed
make[1]: *** [src/CMakeFiles/MultiCraft.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```
Possibly caused by 2974e4fde277b69b79c39c76bc8d23ce4e388ebc

**Comment by MoNTE48** [comment]
@paramat Remove -flto
https://github.com/MultiCraftProject/MultiCraft/commit/d7f6c989e222539d7cd9faecf8802e2982755800#diff-95e351a3805a1dafa85bf20b81d086e6R775
I ask you to help with mapgen's problem a week and a half.  If I do not get a solution to the problem in the near future, I will give this task to another programmer.  If you were not lazy to check mail and would work during the day, like other people, I would help you with the assembly a week ago.

**Comment by MoNTE48** [comment]
If you are interested in working at MultiCraft, then check your email several times a day and be available from 9 am on BST.  You refuse to communicate in the messenger and ask to communicate via email / on github, and at the same time do not respond to emails.

**Comment by paramat** [comment]
I have wanted to work on MultiCraft and the tree log bug since 24th May, but how can i work on MultiCraft if i can't compile it?
I deleted my fork when you stopped development a few months ago.
So i re-forked MultiCraft on 24th May, intending to work on mapgen, but couldn't compile, see #138 , and my fork did not contain the server branch.
So you then deleted the invalid branch and renamed the active branch to 'master'.
So on 26th May i deleted my fork again and reforked MultiCraft, again intending to work on mapgen, but now i can't compile again.

Thanks for the help, will try.

You need to be more patient.
I am actually attending to MultiCraft faster than many MT issues i should be working on, even though MT is a much higher priority for me.
The tree log bug is not extremely urgent, this is only a development version.
I don't like communicating with you by email, please don't email me anymore. You should be communicating here in the repo so that everyone can see what's going on.

I work when i am able to work, i do not have to start work at 9am BST, if the work gets done it doesn't matter when i do it. I am not your employee, i'm working voluntarily.
I cannot work from 9am due to health problems. Besides, everyone lives in different time zones, so you cannot expect people to be awake when you are.
I have no employment obligations to you, you are being ridiculous.

I will not work on the tree log bug. It's easy to generate decorations, all the code is present in MT 0.4.16 to copy, just don't use MT 5.0.0 engine features like 'place_y_offset'.
I will re-create my hell realm PR (for free of course), after that i will do no more work for MultiCraft.
If you want a portal mod, copy the 'nether' mod by PilzAdam, sofar and me, and remove the mapgen code https://github.com/minetest-mods/nether , ask one of your other coders to do this, it's not difficult.

I disapprove of what you are doing with MultiCraft. You are profiting from other people's work, this is legally allowed, but you are cloning Minecraft with no imagination or creativity, adding advertisements, to make money by taking advantage of children with smartphones who 'want Minecraft'. It's little better than the other nasty and corrupt MT app forks.

**Comment by MoNTE48** [comment]
Matthew, please forgive me for problems with building MC. Due to the fact that we all work on different platforms and build different versions of the game, such errors occur. After the next release I will make changes in a separate branch and merge them into the master only after full testing.
I appreciate your help and your code. mapgen_v7p is divine, I have been using it for over a year now. And I would like you to continue developing it.

I'm trying to release MultiCraft 1.2.0 in which the maximum number of problems will be fixed and certain functions added until June 1, and I see that I am not investing in the deadlines. I discover new and new problems. I try to test the game on a server that is constantly falling. I sleep for several hours and constantly wake up at night to copy debug information. Otherwise, in a day I will receive an output file of over a million lines in size (I can send you one if you want).
My budget is quite limited, and I try to do some of the things myself. But I'm not a Lua programmer. And the more I do not know C++.

**I sincerely regret your health problems and would be glad to help you, if possible.**

As you correctly said, there is no difference at what time a person works. But in any development process there should be a stage of discussion, dialogue. You must be sure that you understand me correctly. And I have to be sure that my bad English will not lead to a function that does not meet my expectations! I think you understand that.
I would like to continue working with you because I appreciate your skills. However, I would like to know what time you will be online so that you can come and talk to you. If Github, so Github. The only thing that I do not want to advertise is the amount of donations.

I will explain to you about "copying minecraft". There is always a game that sets a certain bar. In this case, it is Minecraft. If I make a copy of this game, my application will be blocked, and I can go to court, which will not be a very pleasant outcome. I can do everything completely different. Then my game will cease to be interesting to players, the development will be stopped as soon as my budget ends. The game will stop receiving updates, because I will have to deal with other projects, and will die. There are certain things that are well-established in our world. All cars have a similar design and the same control. If I release the car in the form of a carriage from the 18th century, I will sell 5 copies for wedding agencies and go bankrupt. I think you understand the point.

MultiCraft already has a lot of differences from Minecraft, and this list will increase. A handy craftguide will be added to MultiCraft 1.3, after which craft items will be changed to your own. MultiCraft uses high resolution textures (often 64*64). I demand that the items remain clear to the player, but not an adaptation of minecraft. It has cost me several thousand dollars. The development of MultiCraft (code and graphics) has been spent well over 10.000 dollars over the past few years. I think you understand what advertising revenue goes to.
Minetest has no money to pay for the App Store developer account or to draw a normal icon. I have no money to ### finish creating models of mobs, which will be much more beautiful than all that you saw in minetest. Do you want a secret? 1 working day of my designer costs **240 USD.** With advertising revenue, I can allow programmers and designers to work **only a few days a month**. I think that I have sufficiently responded to the complaint about a corrupt MT application.

I beg you to change your mind and help me with the development of the game. As before, I will be happy to give you donations for your help!

**Comment by paramat** [comment]
I can now compile by removing '-flto' in the PR branch i am working on. It's a pain, but issue is resolved.
